# some more ls aliases
#alias ll='ls -l'
alias la='ls -AF'
#alias l='ls -CF'
#alias ll='ls -lAF'
alias ll='LC_COLLATE=C ls -lAF --group-directories-first'

alias tmux='tmux -2'
alias more='less -R'
#alias suapt='sudo apt update && sudo apt upgrade'
#alias sush='sudo shutdown -P now'
alias pdfcut='pdfnup --nup 1x1 --no-landscape'
alias ps='ps axlfww'
#alias scrot='scrot -e "mv $f ~/.scrot"'
alias minicom='minicom -c on --capturefile=$HOME/.minicom/minicom.log'
alias astyle='astyle --style=bsd -s4 -n'
alias ccaly='ccal --y'
alias ccalm='ccal `/usr/bin/date +"%B"`'
alias apg='apg -n 1 -m 64 -x 64 -M SNCL'
alias tidy='tidy -config ~/.tidy.conf -f ~/.tidy/err.log'
alias rsync='rsync -avzP --delete -e ssh'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias date='date +"%F %T"'
alias diff='diff -EbB'
alias df='df -h'
alias du='du -h'
